name: Deck Sync
on:
  push:
    branches:
      - main
env:
  DECK_KONNECT_TOKEN: ${{ secrets.DECK_KONNECT_TOKEN }}
jobs:
  deploy:
      name: Deck sync
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: source bin/getDeckAction.sh
        - run: ./deck diff --konnect-runtime-group-name=fly-io-iad runtime-groups/fly-io-iad
