name: Deck Sync
on:
  push:
    branches:
      - main
env:
  DECK_KONNECT_TOKEN: ${{ secrets.DECK_KONNECT_TOKEN }}
jobs:
  deploy:
      name: Deck sync
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: giantswarm/install-binary-action@v1.0.0
          with:
              binary: "deck"
              version: "v1.17.1"
              download_url: "https://github.com/Kong/deck/releases/download/v1.17.1/deck_1.17.1_linux_amd64.tar.gz"
              tarball_binary_path: "${binary}"
              smoke_test: "${binary} version"
        - run: deck diff --konnect-runtime-group-name=fly-io-iad runtime-groups/fly-io-iad
